# Alembic Configuration File

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)s_%%(created_datetime)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to datetime.datetime.now(timezone.utc).astimezone(sqlalchemy_utils.timezone)
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field in the migration file name template;
# set to 0 to omit the slug from the file name entirely
# affects the filename of migration files
# defaults to 40
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# When set to "true", this option enables the environment to
# This is a bit of a misnomer, as Alembic itself
# only outputs a timestamp for revisions. But this option works with
# this scripts' environment.
# setting the version identifier location to a custom string location for both
# migrations support and initialization.
# When this option is True, the directory location given by 'script_location'
# is treated as a dotted import path, not a file location.
#
# sqlalchemy_url should be set, but will not be used during any
# of the Alembic command handling functions, only during migration itself
# and by custom commands that may add it to the context.migrate() call.
#
sqlalchemy.url = driver://user:pass@localhost/dbname

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
